[settings]
disable_backends = ["asdf"] # cannot be updated by Renovate

[tools]
pipx = "latest"
"pipx:cruft" = "latest"
terraform = "latest"

[tasks]
"repos:init" = { dir = "repos", run = "terraform init", description = "Initialise repos state" }
"repos:fmt" = { dir = "repos", run = "terraform fmt", description = "Format repos configuration" }
"repos:plan" = { dir = "repos", run = "terraform plan", description = "Plan repos changes" }
"repos:apply" = { dir = "repos", run = "terraform apply", description = "Apply repos changes" }
"repos:adopt" = { dir = "repos", run = "../scripts/adopt-repo.sh", description = "Adopt an existing repo" }
"template:update" = { run = "cruft update", description = "Update project with the latest changes from the template" }
"template:restore" = { run = "cruft diff | git apply", description = "Restore template-managed files" }
