name: Renovate

on:
  schedule:
    # Schedules aren't reliable, spam runs in the hope of landing in the Renovate window
    - cron: "30 18-23 * * 0"
    - cron: "30 0-3 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@e26264186543fd355dc60776e21f7fbb67ce6f85 # v46.3.2
        with:
          renovate-version: 44.104.2@sha256:c87b1c55ab98286dad9df0c1d84ebe1fbe2a805a68d48dd7a6d577709bf951a7
          token: ${{ secrets.RENOVATE_TOKEN || github.token }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ALLOWED_COMMANDS: '[".+"]'
